analysis:
  pca_components: 200
  percentile_thresholds:
  - 10
  - 90
  top_pcs_count: 5
  umap_dimensions: 3
display:
  title: AI Rating vs Social Class Analysis
variables:
  X:
    max_value: 10
    min_value: 1
    name: AI Rating
    short_name: AI
  Y:
    max_value: 5
    min_value: 1
    name: Social Class
    short_name: SC
