analysis:
  pca_components: 200
  percentile_thresholds:
  - 10
  - 90
  top_pcs_count: 5
  umap_dimensions: 3
display:
  title: X vs Y Analysis
variables:
  X:
    max_value: 5
    min_value: 1
    name: X Variable
    short_name: X
  Y:
    max_value: 10
    min_value: 1
    name: Y Variable
    short_name: Y
